import {
  IsString,
  IsNotEmpty,
  IsNumber,
  ValidateNested,
} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class PaymentMethodDto {
  @IsNotEmpty()
  @IsString()
  @ApiProperty({
    example: 'CARD',
    description: 'The payment method',
  })
  type: string;
  @IsNotEmpty()
  @IsString()
  @ApiProperty({
    example: 'tok_prod_280_32326B334c47Ec49a516bf1785247ba2',
    description: 'The token generated by the payment gateway',
  })
  token: string;

  @IsNotEmpty()
  @IsNumber()
  @ApiProperty({
    example: 2,
    description: 'Installments number',
  })
  installments: number;
}

export class PaymentBodyDto {
  @IsNotEmpty()
  @ApiProperty({
    example:
      'eyJhbGciOiJIUzI1NiJ9.eyJjb250cmFjdF9pZCI6MSwicGVybWFsaW5rIjoiaHR0cHM6Ly93b21waS5jby93cC1jb250ZW50L3VwbG9hZHMvMjAxOS8wOS9URVJNSU5PUy1ZLUNPTkRJQ0lPTkVTLURFLVVTTy1VU1VBUklPUy1XT01QSS5wZGYiLCJmaWxlX2hhc2giOiIzZGNkMGM5OGU3NGFhYjk3OTdjZmY3ODExNzMxZjc3YiIsImppdCI6IjE1ODU4NDE2MTUtNDU2MTgiLCJleHAiOjE1ODU4NDUyMTV9.bwBa-RjN3euycqeXVroLWwUN1ZRY1X11I4zn1y5nMiY',
    description: 'The token generated by the payment gateway',
  })
  acceptance_token: string;

  @IsNotEmpty()
  @ApiProperty({
    example: '123456',
    description: 'The session id generated by the payment gateway',
  })
  session_id: string;

  @ValidateNested()
  @ApiProperty({
    type: PaymentMethodDto,
    description: 'The payment method',
    example: {
      type: 'CARD',
      token: 'tok_prod_280_32326B334c47Ec49a516bf1785247ba2',
      installments: 2,
    },
  })
  payment_method: PaymentMethodDto;

  @IsNotEmpty()
  @ApiProperty({
    example: '3232-3232',
    description: 'The ID of the transaction',
  })
  transaction_id: string;

  @IsNotEmpty()
  @ApiProperty({
    example: '12345',
    description: 'The ID of the client',
  })
  id_client: number;
}

export class TransactionDto {
  @IsNotEmpty()
  @ApiProperty({
    example: '12345',
    description: 'The ID of the client',
  })
  idClient: number;

  @IsNotEmpty()
  @IsString()
  @ApiProperty({
    example: 'ABC123456',
    description: 'The identification of the client',
  })
  identificationClient: string;

  @IsNotEmpty()
  @IsString()
  @ApiProperty({
    example: 'ABC123456',
    description: 'Productos comprados en la transaccion',
  })
  productsTransaction: string;

  @IsNotEmpty()
  @IsNumber()
  @ApiProperty({
    example: 123456,
    description: 'El total de la transacción, incluyendo impuestos',
  })
  totalTransaction: number;

  @IsNotEmpty()
  @IsNumber()
  @ApiProperty({
    example: 100000,
    description: 'El total de la transacción, sin impuestos',
  })
  totalTransactionWhitoutTaxes: number;

  @IsNotEmpty()
  @IsNumber()
  @ApiProperty({
    example: 23456,
    description: 'El total de los impuestos de la transacción',
  })
  taxesTransaction: number;

  @IsNotEmpty()
  @IsString()
  @ApiProperty({
    example: '+1234567890',
    description: 'The phone number of the client',
  })
  phoneClient: string;

  @IsNotEmpty()
  @IsString()
  @ApiProperty({
    example: 'client@example.com',
    description: 'The email of the client',
  })
  emailClient: string;

  @IsNotEmpty()
  @IsString()
  @ApiProperty({
    example: 'New York',
    description: 'The city of the client',
  })
  cityClient: string;

  @IsNotEmpty()
  @IsString()
  @ApiProperty({
    example: '1234 Elm Street',
    description: 'The address of the client',
  })
  adressClient: string;
}
