export const {
  PORT = 3000,
  WOMPI_PUBLIC_KEY = '',
  WOMPI_PRIVATE_KEY = '',
  WOMPI_API_URL = '',
  WOMPI_INTEGRITY_KEY = '',
  AWS_SECRET_ACCESS_KEY = '',
  AWS_ACCESS_KEY = '',
} = process.env;
